export enum CaptchaType {
  image = 'image',
  audio = 'audio',
}

export enum Theme {
  light = 'light',
  dark = 'dark',
}

export enum Size {
  normal = 'normal',
  compact = 'compact',
}

// to ensure that the passed lang is supported we expose the supported langs
// all of these languages are taken from
// this list: https://developers.google.com/recaptcha/docs/language
export enum CaptchaLang {
  Arabic = 'ar',
  Afrikaans = 'af',
  Amharic = 'am',
  Armenian = 'hy',
  Azerbaijani = 'az',
  Basque = 'eu',
  Bengali = 'bn',
  Bulgarian = 'bg',
  Catalan = 'ca',
  ChineseHongKong = 'zh-HK',
  ChineseSimplified = 'zh-CN',
  ChineseTraditional = 'zh-TW',
  Croatian = 'hr',
  Czech = 'cs',
  Danish = 'da',
  Dutch = 'nl',
  EnglishUK = 'en-GB',
  EnglishUS = 'en',
  Estonian = 'et',
  Filipino = 'fil',
  Finnish = 'fr',
  FrenchCanadian = 'fr-CA',
  Galician = 'gl',
  Georgian = 'ka',
  German = 'de',
  GermanAustria = 'de-AT',
  GermanSwitzerland = 'de-CH',
  Greek = 'el',
  Gujarati = 'gu',
  Hebrew = 'iw',
  Hindi = 'hi',
  Hungarain = 'hu',
  Icelandic = 'is',
  Indonesian = 'id',
  Italian = 'it',
  Japanese = 'ja',
  Kannada = 'kn',
  Korean = 'ko',
  Laothian = 'lo',
  Latvian = 'lv',
  Lithuanian = 'lt',
  Malay = 'ms',
  Malayalam = 'ml',
  Marathi = 'mr',
  Mongolian = 'mn',
  Norwegian = 'no',
  Persian = 'fa',
  Polish = 'pl',
  Portuguese = 'pt',
  PortugueseBrazil = 'pt-BR',
  PortuguesePortugal = 'pt-PT',
  Romanian = 'ro',
  Russian = 'ru',
  Serbian = 'sr',
  Sinhalese = 'si',
  Slovak = 'sk',
  Slovenian = 'sl',
  Spanish = 'es',
  SpanishLatinAmerica = 'es-419',
  Swahili = 'sw',
  Swedish = 'sv',
  Tamil = 'ta',
  Telugu = 'te',
  Thai = 'th',
  Turkish = 'tr',
  Ukrainian = 'uk',
  Urdu = 'ur',
  Vietnamese = 'vi',
  Zulu = 'zu',
}
