import { IconMetadata } from "../../types";

const tpaIconsMetadata: Array<IconMetadata> = [
  {
    title: "Calendar",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"CalendarLarge" },
  },
  {
    title: "Clock",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"ClockLarge" },
  },
  {
    title: "Comment",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"CommentLarge" },
  },
  {
    title: "Document",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"DocumentLarge" },
  },
  {
    title: "Email",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"EmailLarge" },
  },
  {
    title: "Percent",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"PercentLarge" },
  },
  {
    title: "Reaction",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"ReactionLarge" },
  },
  {
    title: "Tag",
    category: "General",
    description: "",
    tags: [],
    sizes: { "30":"TagLarge" },
  },
  {
    title: "Check",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"CheckXSmall" },
  },
  {
    title: "Close",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"12":"CloseXXSmall", "16":"CloseXSmall", "30":"CloseLarge" },
  },
  {
    title: "Delete",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "30":"DeleteLarge" },
  },
  {
    title: "Edit",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "30":"EditLarge" },
  },
  {
    title: "ExternalLink",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "30":"ExternalLinkLarge" },
  },
  {
    title: "Link",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "30":"LinkLarge" },
  },
  {
    title: "Minus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"MinusXSmall", "30":"MinusLarge" },
  },
  {
    title: "Plus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"PlusXSmall", "30":"PlusLarge" },
  },
  {
    title: "LikeHeart",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "30":"LikeHeartLarge", },
  },
  {
    title: "LikeHeartFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "30":"LikeHeartFillLarge" },
  },
  {
    title: "LockFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: {"16":"LockFillXSmall" },
  },
  {
    title: "Select",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "30":"SelectLarge" },
  },
  {
    title: "SelectFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "30":"SelectFillLarge" },
  },
  {
    title: "Visible",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "30":"VisibleLarge" },
  },
  {
    title: "Camera",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "30":"CameraLarge" },
  },
  {
    title: "Image",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "30":"ImageLarge" },
  },
  {
    title: "PlayButton",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "30":"PlayButtonLarge" },
  },
  {
    title: "PlayFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "30":"PlayFillLarge" },
  },
  {
    title: "Video",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "30":"VideoLarge" },
  },
  {
    title: "VideoFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "16":"VideoFillXSmall" },
  },
  {
    title: "Error",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "30":"ErrorLarge" },
  },
  {
    title: "Notifications",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "30":"NotificationsLarge" },
  },
  {
    title: "NotificationsFill",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "30":"NotificationsFillLarge" },
  },
  {
    title: "ArrowDown",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowDownXSmall", "30":"ArrowDownLarge", "60":"ArrowDownXLarge" },
  },
  {
    title: "ArrowLeft",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowLeftXSmall", "30":"ArrowLeftLarge", "60":"ArrowLeftXLarge" },
  },
  {
    title: "ArrowRight",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowRightXSmall", "30":"ArrowRightLarge", "60":"ArrowRightXLarge" },
  },
  {
    title: "ArrowUp",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowUpXSmall", "30":"ArrowUpLarge", "60":"ArrowUpXLarge" },
  },
  {
    title: "DoubleArrowRight",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "30":"DoubleArrowRightLarge" },
  },
  {
    title: "DoubleArrowLeft",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "30":"DoubleArrowLeftLarge" },
  },
  {
    title: "Blog",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"BlogLarge" },
  },
  {
    title: "Bookings",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"BookingsLarge" },
  },
  {
    title: "Events",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"EventsLarge" },
  },
  {
    title: "Forums",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"ForumsLarge" },
  },
  {
    title: "Hotels",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"HotelsLarge" },
  },
  {
    title: "Stores",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "30":"StoresLarge" },
  },
  {
    title: "SpoilerAlert",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "40":"SpoilerAlertLarge" },
  },
];

export default tpaIconsMetadata;
