# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"
skip_tags: true 
environment:
  matrix:
    - nodejs_version: "12.10.0"

install:
  - choco install -y googlechrome
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cd packages\wix-ui-core
  - npm install
  - npm run build
  - npm run test
