const files = [
  ['address-input.js', 43],
  ['autocomplete.js', 33],
  ['avatar.js', 14],
  ['button-next.js', 8],
  ['captcha.js', 9],
  ['checkbox.js', 7],
  ['circular-progress-bar.js', 7],
  ['click-outside.js', 5],
  ['dropdown-content.js', 9],
  ['dropdown-option.js', 7],
  ['dropdown.js', 31],
  ['ellipsis-tooltip.js', 8],
  ['file-picker-button.js', 7],
  ['horizontal-menu.js', 9],
  ['icon-with-options.js', 32],
  ['image.js', 6],
  ['input-with-options.js', 33],
  ['input.js', 6],
  ['label-with-options.js', 33],
  ['linear-progress-bar.js', 7],
  ['loadable.js', 5],
  ['media-image.js', 13],
  ['menu-item.js', 6],
  ['nav-stepper.js', 7],
  ['pagination.js', 10],
  ['popover.js', 28],
  ['popover-next.js', 12],
  ['radio-button.js', 7],
  ['signature-input.js', 11],
  ['slider.js', 10],
  ['stepper.js', 5],
  ['tags-list.js', 7],
  ['thumbnail.js', 6],
  ['time-picker.js', 9],
  ['toggle-switch.js', 6],
  ['tooltip.js', 29],
  ['video.js', 88],
];

module.exports = {
  bundleSize: {
    files: files.map(([name, size]) => ({
      maxSize: `${size}kb`,
      glob: `bundles/${name}`,
    })),
  },
};
