export const systemIcons = [
  {
    'title': 'Crop',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Crop'},
  }, {
    'title': 'CropBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CropBold'},
  }, {
    'title': 'MoveBackward',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveBackward'},
  }, {
    'title': 'MoveBackwardBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveBackwardBold'},
  }, {
    'title': 'MoveForward',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveForward'},
  }, {
    'title': 'MoveForwardBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveForwardBold'},
  }, {
    'title': 'Rotation',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Rotation'},
  }, {
    'title': 'Hide',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'HideSmall', '24': 'Hide'},
  }, {
    'title': 'HideBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HideBold'},
  }, {
    'title': 'Lock',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'LockSmall', '24': 'Lock'},
  }, {
    'title': 'LockBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'LockBold'},
  }, {
    'title': 'Settings',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'18': 'SettingsSmall', '24': 'Settings'},
  }, {
    'title': 'SettingsBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SettingsBold'},
  }, {
    'title': 'Help',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Help'},
  }, {
    'title': 'ApplyTo',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ApplyTo'},
  }, {
    'title': 'Copy',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Copy'},
  }, {
    'title': 'CopyBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CopyBold'},
  }, {
    'title': 'Duplicate',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Duplicate'},
  }, {'title': 'DuplicateBold', 'category': 'Actions', 'description': '', 'tags': [], 'sizes': {'24': 'DuplicateBold'}},
]
