import { IconMetadata } from "../types";

const tpaIconsMetadata: Array<IconMetadata> = [
  {
    title: "LikeHeart",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "20":"LikeHeartSmall", "24":"LikeHeart", "30":"LikeHeartLarge", },
  },
  {
    title: "LikeHeartFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "20":"LikeHeartFillSmall", "24":"LikeHeartFill", "30":"LikeHeartFillLarge" },
  },
  {
    title: "Lock",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "24":"Lock"  },
  },
  {
    title: "LockFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: {"16":"LockFillXSmall","20":"LockFillSmall", "24":"LockFill", },
  },
  {
    title: "Select",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "20":"SelectSmall", "24":"Select", "30":"SelectLarge" },
  },
  {
    title: "CheckFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "24":"CheckFill" , "30":"CheckFillLarge" },
  },
  {
    title: "Unlock",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "24":"Unlock"  },
  },
  {
    title: "UnlockFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "24":"UnlockFill" },
  },
  {
    title: "Visible",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "20":"VisibleSmall", "24":"Visible", "30":"VisibleLarge" },
  },
  {
    title: "VisibleFill",
    category: "Toggle",
    description: "",
    tags: [],
    sizes: { "20": "VisibleFillSmall" },
  },
  {
    title: "AlignCenter",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"AlignCenterSmall" },
  },
  {
    title: "AlignLeft",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"AlignLeftSmall" },
  },
  {
    title: "AlignRight",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"AlignRightSmall" },
  },
  {
    title: "Blog",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"BlogSmall", "24":"Blog", "30":"BlogLarge" },
  },
  {
    title: "Bold",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"BoldSmall" },
  },
  {
    title: "Bookings",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"BookingsSmall", "30":"BookingsLarge" },
  },
  {
    title: "BulletedList",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"BulletedListSmall" },
  },
  {
    title: "DecreaseIndent",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"DecreaseIndentSmall" },
  },
  {
    title: "Events",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"EventsSmall", "30":"EventsLarge" },
  },
  {
    title: "Forums",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"ForumsSmall", "24":"Forums", "30":"ForumsLarge" },
  },
  {
    title: "HighlightColor",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"HighlightColorSmall" },
  },
  {
    title: "Hotels",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"HotelsSmall", "24":"Hotels", "30":"HotelsLarge" },
  },
  {
    title: "IncreaseIndent",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"IncreaseIndentSmall" },
  },
  {
    title: "Italic",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"ItalicSmall" },
  },
  {
    title: "Justify",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"JustifySmall" },
  },
  {
    title: "LineSpacing",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"LineSpacingSmall" },
  },
  {
    title: "NumberedList",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"NumberedListSmall" },
  },
  {
    title: "Quote",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"QuoteSmall" },
  },
  {
    title: "Snippet",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"SnippetSmall" },
  },
  {
    title: "SpoilerAlert",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "30":"SpoilerAlertLarge" },
  },
  {
    title: "Stores",
    category: "WixBrands",
    description: "",
    tags: [],
    sizes: { "20":"StoresSmall", "24":"Stores", "30":"StoresLarge" },
  },
  {
    title: "TextColor",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"TextColorSmall" },
  },
  {
    title: "TextStyle",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"TextStyleSmall" },
  },
  {
    title: "TextStyle1",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"TextStyle1Small" },
  },
  {
    title: "TextStyle2",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"TextStyle2Small" },
  },
  {
    title: "Underline",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"UnderlineSmall" },
  },
  {
    title: "WhiteTextColor",
    category: "RCE",
    description: "",
    tags: [],
    sizes: { "20":"WhiteTextColorSmall" },
  },
  {
    title: "Check",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"CheckXSmall", "20":"CheckSmall", "24":"Check" },
  },
  {
    title: "Close",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"12":"CloseXXSmall", "16":"CloseXSmall", "20":"CloseSmall", "24":"Close", "30":"CloseLarge" },
  },
  {
    title: "Delete",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"DeleteSmall", "24":"Delete", "30":"DeleteLarge" },
  },
  {
    title: "Download",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "24":"Download" },
  },
  {
    title: "Duplicate",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"DuplicateSmall", "24":"Duplicate" },
  },
  {
    title: "DuplicateFill",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "20":"DuplicateFillSmall", "24":"DuplicateFill" },
  },
  {
    title: "Edit",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "20":"EditSmall", "24":"Edit", "30":"EditLarge" },
  },
  {
    title: "ExternalLink",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"ExternalLinkSmall", "24":"ExternalLink", "30":"ExternalLinkLarge" },
  },
  {
    title: "Link",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"LinkSmall", "24":"Link", "30":"LinkLarge" },
  },
  {
    title: "Minus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"MinusXSmall", "20":"MinusSmall", "24":"Minus", "30":"MinusLarge" },
  },
  {
    title: "More",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"MoreSmall", "24":"More" },
  },
  {
    title: "MoveTo",
    category: "Actions",
    description: "",
    tags: [],
    sizes: { "24":"MoveTo" },
  },
  {
    title: "Plus",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"16":"PlusXSmall", "20":"PlusSmall", "24":"Plus", "30":"PlusLarge" },
  },
  {
    title: "Rearrangeable",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"24":"Rearrangeable"},
  },
  {
    title: "Search",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"20":"SearchSmall", "24":"Search" },
  },
  {
    title: "Share",
    category: "Actions",
    description: "",
    tags: [],
    sizes: {"24":"Share" },
  },
  {
    title: "AddUser",
    category: "General",
    description: "",
    tags: [],
    sizes: {"24":"AddUser" },
  },
  {
    title: "Admin",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"AdminSmall", "24":"Admin" },
  },
  {
    title: "AdminFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"AdminFillSmall", "24":"AdminFill" },
  },
  {
    title: "Badge",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Badge" },
  },
  {
    title: "BadgeFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"BadgeFill" },
  },
  {
    title: "BlockComments",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"BlockComments" },
  },
  {
    title: "Calendar",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"CalendarSmall", "24":"Calendar", "30":"CalendarLarge" },
  },
  {
    title: "Clock",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"ClockSmall", "24":"Clock", "30":"ClockLarge" },
  },
  {
    title: "Comment",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"CommentSmall", "24":"Comment", "30":"CommentLarge" },
  },
  {
    title: "CommentFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"CommentFillSmall", "24":"CommentFill" },
  },
  {
    title: "Document",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"DocumentSmall", "24":"Document", "30":"DocumentLarge" },
  },
  {
    title: "DocumentFill",
    category: "General",
    description: "",
    tags: [],
    sizes: {"20":"DocumentFillSmall" },
  },
  {
    title: "Email",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"EmailSmall", "24":"Email", "30":"EmailLarge" },
  },
  {
    title: "Folder",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Folder" },
  },
  {
    title: "Group",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Group" },
  },
  {
    title: "GroupFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"GroupFill" },
  },
  {
    title: "Location",
    category: "General",
    description: "",
    tags: [],
    sizes: {"20":"LocationSmall", "24":"Location" },
  },
  {
    title: "LocationFill",
    category: "General",
    description: "",
    tags: [],
    sizes: {"24":"LocationFill" },
  },
  {
    title: "Percent",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Percent", "30":"PercentLarge" },
  },
  {
    title: "Phone",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"PhoneSmall", "24":"Phone" },
  },
  {
    title: "Pin",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Pin" },
  },
  {
    title: "Price",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Price" },
  },
  {
    title: "PriceFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"PriceFill" },
  },
  {
    title: "Pulic",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Public" },
  },
  {
    title: "PulicFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"PublicFill" },
  },
  {
    title: "Reaction",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"ReactionSmall", "24":"Reaction", "30":"ReactionLarge" },
  },
  {
    title: "Reply",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"Reply" },
  },

  {
    title: "Settings",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"SettingsSmall", "24":"Settings", "30":"SettingsLarge" },
  },
  {
    title: "SettingsFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"SettingsFillSmall" },
  },
  {
    title: "ShoppingBag",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"ShoppingBag" },
  },
  {
    title: "ShoppingBagFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"ShoppingBagFill" },
  },
  {
    title: "SoundOff",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"SoundOff" },
  },
  {
    title: "SoundOffFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"SoundOffFill" },
  },
  {
    title: "SoundOn",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"SoundOn" },
  },
  {
    title: "SoundOnFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"SoundOnFill" },
  },
  {
    title: "Tag",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"TagSmall", "24":"Tag", "30":"TagLarge" },
  },
  {
    title: "TagFill",
    category: "General",
    description: "",
    tags: [],
    sizes: { "20":"TagFillSmall", "24":"TagFill" },
  },
  {
    title: "ThumbUp",
    category: "General",
    description: "",
    tags: [],
    sizes: { "24":"ThumbUp" },
  },
  {
    title: "Camera",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"CameraSmall", "24":"Camera", "30":"CameraLarge" },
  },
  {
    title: "CameraFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"CameraFillSmall", "24":"CameraFill" },
  },
  {
    title: "Image",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"ImageSmall", "24":"Image", "30":"ImageLarge" },
  },
  {
    title: "PlayButton",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"PlayButtonSmall", "24":"PlayButton", "30":"PlayButtonLarge" },
  },
  {
    title: "PlayButtonFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"PlayButtonFillSmall" },
  },
  {
    title: "PlayFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"PlayFillSmall", "24":"PlayFill", "30":"PlayFillLarge" },
  },
  {
    title: "Video",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "20":"VideoSmall", "24":"Video", "30":"VideoLarge" },
  },
  {
    title: "VideoFill",
    category: "Media",
    description: "",
    tags: [],
    sizes: { "16":"VideoFillXSmall", "20":"VideoFillSmall", "24":"VideoFill" },
  },
  {
    title: "Alert",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "24":"Alert" },
  },
  {
    title: "Error",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "20":"ErrorSmall", "24":"Error", "30":"ErrorLarge" },
  },
  {
    title: "ErrorFill",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "20":"ErrorFillSmall" },
  },
  {
    title: "Info",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "24":"Info" },
  },
  {
    title: "Notifications",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: { "20":"NotificationsSmall", "24":"Notifications", "30":"NotificationsLarge" },
  },
  {
    title: "NotificationsFill",
    category: "Notifications",
    description: "",
    tags: [],
    sizes: {"20":"NotificationsFillSmall", "30":"NotificationsFillLarge" },
  },
  {
    title: "ArrowDown",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowDownXSmall", "20":"ArrowDownSmall", "24":"ArrowDown", "30":"ArrowDownLarge", "60":"ArrowDownXLarge" },
  },
  {
    title: "ArrowLeft",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowLeftXSmall", "20":"ArrowLeftSmall", "24":"ArrowLeft", "30":"ArrowLeftLarge", "60":"ArrowLeftXLarge" },
  },
  {
    title: "ArrowRight",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowRightXSmall", "20":"ArrowRightSmall", "24":"ArrowRight", "30":"ArrowRightLarge", "60":"ArrowRightXLarge" },
  },
  {
    title: "ArrowUp",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "16":"ArrowUpXSmall", "20":"ArrowUpSmall", "24":"ArrowUp", "30":"ArrowUpLarge", "60":"ArrowUpXLarge" },
  },
  {
    title: "DoubleArrowRight",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "24":"DoubleArrowRight", "30":"DoubleArrowRightLarge" },
  },
  {
    title: "DoubleArrowLeft",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "24":"DoubleArrowLeft", "30":"DoubleArrowLeftLarge" },
  },
  {
    title: "Maximize",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "20":"MaximizeSmall", "24":"Maximize" },
  },
  {
    title: "Minimize",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "20":"MinimizeSmall", "24":"Minimize" },
  },
  {
    title: "Sort",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "24":"Sort" },
  },
  {
    title: "SortDown",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "24":"SortDown" },
  },
  {
    title: "SortUp",
    category: "Arrows",
    description: "",
    tags: [],
    sizes: { "24":"SortUp" },
  },
  /*
  {
    title: "DevianArt",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"DevianArt" },
  },
  {
    title: "FB",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"FB" },
  },
  {
    title: "GooglePodcast",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"GooglePodcast" },
  },
  {
    title: "Instagram",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Instagram" },
  },
  {
    title: "Linkdin",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Linkdin" },
  },
  {
    title: "Odnoklassniki",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Odnoklassniki" },
  },
  {
    title: "Pinterest",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Pinterest" },
  },
  {
    title: "Podcast",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Podcast" },
  },
  {
    title: "RSS",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"RSS" },
  },
  {
    title: "SoundCloud",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"SoundCloud" },
  },
  {
    title: "Spotify",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Spotify" },
  },
  {
    title: "Stitcher",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Stitcher" },
  },
  {
    title: "TikTok",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"TikTok" },
  },
  {
    title: "Tumblr",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Tumblr" },
  },
  {
    title: "Twitter",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Twitter" },
  },
  {
    title: "Vimeo",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Vimeo" },
  },
  {
    title: "VKontakte",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"VKontakte" },
  },
  {
    title: "Youtube",
    category: "Social",
    description: "",
    tags: [],
    sizes: { "24":"Youtube" },
  },*/
];

export default tpaIconsMetadata;
