import { IconMetadata } from "../types";

export const deprecatedSystemIcons: Array<string> = [];

const systemIconsMetadata: Array<IconMetadata> = [
  {
    title: "AddItem",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: {
      "23": "AddItemSmall",
      "47": "AddItemMedium",
      "63": "AddItemLarge",
    },
  },
  {
    title: "AddMedia",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "31": "AddMedia" },
  },
  {
    title: "BreadcrumbsChevronRight",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "6x14": "BreadcrumbsChevronRight" },
  },
  {
    title: "CheckboxChecked",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "10x8": "CheckboxChecked" },
  },
  {
    title: "CheckboxIndeterminate",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "8x2": "CheckboxIndeterminate" },
  },
  {
    title: "CircleLoaderCheck",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "19x14": "CircleLoaderCheck", "11x8": "CircleLoaderCheckSmall" },
  },
  {
    title: "Close",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "6": "Close", "8": "CloseLarge" },
  },
  {
    title: "DragAndDrop",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "7x12": "DragAndDropSmall", "18x24": "DragAndDropLarge" },
  },
  {
    title: "DragAndDropLocked",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "18x24": "DragAndDropLockedLarge" },
  },
  {
    title: "DropDownArrow",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "10x6": "DropDownArrow" },
  },
  {
    title: "FaceDisapointed",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "FaceDisapointed30" },
  },
  {
    title: "FaceFrowning",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "FaceFrowning30" },
  },
  {
    title: "FaceGrining",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "FaceGrining30" },
  },
  {
    title: "FaceNeutral",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "FaceNeutral30" },
  },
  {
    title: "FaceSmiling",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "FaceSmiling30" },
  },
  {
    title: "FormFieldError",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "2x10": "FormFieldError", "2x10 (small)": "FormFieldErrorSmall" },
  },
  {
    title: "FormFieldErrorFilled",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "18": "FormFieldErrorFilled" },
  },
  {
    title: "FormFieldSpinnerDown",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "8x5": "FormFieldSpinnerDown" },
  },
  {
    title: "FormFieldSpinnerUp",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "8x5": "FormFieldSpinnerUp" },
  },
  {
    title: "FormFieldWarningFilled",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "18x16": "FormFieldWarningFilled" },
  },
  {
    title: "HeaderBackButton",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "HeaderBackButton" },
  },
  {
    title: "Help",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "24": "Help24" },
  },
  {
    title: "Move",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "21": "Move", "36": "MoveLarge" },
  },
  {
    title: "SocialButtonFacebook",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "SocialButtonFacebook" },
  },
  {
    title: "SocialButtonInstagram",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "SocialButtonInstagram" },
  },
  {
    title: "SocialButtonLinkedIn",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "SocialButtonLinkedIn" },
  },
  {
    title: "SocialButtonPinterest",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "SocialButtonPinterest" },
  },
  {
    title: "SocialButtonTwitter",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "SocialButtonTwitter" },
  },
  {
    title: "SocialButtonYoutube",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "24x17": "SocialButtonYoutube" },
  },
  {
    title: "SortByArrowDown",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "9x11": "SortByArrowDown" },
  },
  {
    title: "SortByArrowUp",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "9x11": "SortByArrowUp" },
  },
  {
    title: "StarFilled",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "12": "StarFilledTiny", "36": "StarFilledLarge" },
  },
  {
    title: "Star",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "36": "StarLarge" },
  },
  {
    title: "TextAreaAlignCenter",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaAlignCenter" },
  },
  {
    title: "TextAreaAlignJustify",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaAlignJustify" },
  },
  {
    title: "TextAreaAlignLeft",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaAlignLeft" },
  },
  {
    title: "TextAreaAlignRight",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaAlignRight" },
  },
  {
    title: "TextAreaBold",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaBold" },
  },
  {
    title: "TextAreaBulletList",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaBulletList" },
  },
  {
    title: "TextAreaImage",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaImage" },
  },
  {
    title: "TextAreaItalic",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaItalic" },
  },
  {
    title: "TextAreaLeftToRight",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaLeftToRight" },
  },
  {
    title: "TextAreaLink",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaLink" },
  },
  {
    title: "TextAreaNumberedList",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaNumberedList" },
  },
  {
    title: "TextAreaRightToLeft",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaRightToLeft" },
  },
  {
    title: "TextAreaTable",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaTable" },
  },
  {
    title: "TextAreaTextColor",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaTextColor" },
  },
  {
    title: "TextAreaUnderline",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "30": "TextAreaUnderline" },
  },
  {
    title: "ToggleOff",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "8x2": "ToggleOffSmall", "10x2": "ToggleOff" },
  },
  {
    title: "ToggleOn",
    category: undefined,
    description: undefined,
    tags: [],
    sizes: { "9x7": "ToggleOnSmall", "10x8": "ToggleOn" },
  },
];

export default systemIconsMetadata;
