/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/standalone-testkits/protractor.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
module.exports = {
  ...require("./../dist/standalone/src/components/address-input/AddressInput.protractor.driver"),
  ...require("./../dist/standalone/src/components/autocomplete/Autocomplete.protractor.driver"),
  ...require("./../dist/standalone/src/components/checkbox/Checkbox.protractor.driver"),
  ...require("./../dist/standalone/src/components/circular-progress-bar/CircularProgressBar.protractor.driver"),
  ...require("./../dist/standalone/src/components/dropdown/Dropdown.protractor.driver"),
  ...require("./../dist/standalone/src/components/dropdown-content/DropdownContent.protractor.driver"),
  ...require("./../dist/standalone/src/components/dropdown-option/DropdownOption.protractor.driver"),
  ...require("./../dist/standalone/src/components/input/Input.protractor.driver"),
  ...require("./../dist/standalone/src/components/input-with-options/InputWithOptions.protractor.driver"),
  ...require("./../dist/standalone/src/components/label-with-options/LabelWithOptions.protractor.driver"),
  ...require("./../dist/standalone/src/components/linear-progress-bar/LinearProgressBar.protractor.driver"),
  ...require("./../dist/standalone/src/components/nav-stepper/NavStepper.protractor.driver"),
  ...require("./../dist/standalone/src/components/pagination/Pagination.protractor.driver"),
  ...require("./../dist/standalone/src/components/popover/Popover.protractor.driver"),
  ...require("./../dist/standalone/src/components/radio-button/RadioButton.protractor.driver"),
  ...require("./../dist/standalone/src/components/slider/Slider.protractor.driver"),
  ...require("./../dist/standalone/src/components/thumbnail/Thumbnail.protractor.driver"),
  ...require("./../dist/standalone/src/components/time-picker/TimePicker.protractor.driver"),
  ...require("./../dist/standalone/src/components/toggle-switch/ToggleSwitch.protractor.driver"),
  ...require("./../dist/standalone/src/components/tooltip/Tooltip.protractor.driver"),
  ...require("./../dist/standalone/src/components/deprecated/stylable-badge/Badge.protractor.driver"),
  ...require("./../dist/standalone/src/components/deprecated/button/Button.protractor.driver"),
  ...require("./../dist/standalone/src/components/deprecated/divider/Divider.protractor.driver"),
  ...require("./../dist/standalone/src/components/deprecated/label/Label.protractor.driver"),

};
