/* eslint-disable */
/* tslint:disable */
/*
 * DO NOT EDIT THIS FILE!
 * YOUR CHANGES WILL BE OVERWRITTEN!
 * FILE IS BASED ON .wuf/standalone-testkits/vanilla.template.ejs
 * AND GENERATED BY `wuf export-teskits`
 */
module.exports = {
  ...require("./../dist/standalone/src/components/address-input/AddressInput.driver"),
  ...require("./../dist/standalone/src/components/autocomplete/Autocomplete.driver"),
  ...require("./../dist/standalone/src/components/avatar/avatar.driver"),
  ...require("./../dist/standalone/src/components/button-next/button-next.driver"),
  ...require("./../dist/standalone/src/components/captcha/Captcha.driver"),
  ...require("./../dist/standalone/src/components/checkbox/Checkbox.driver"),
  ...require("./../dist/standalone/src/components/circular-progress-bar/CircularProgressBar.driver"),
  ...require("./../dist/standalone/src/components/dropdown/Dropdown.driver"),
  ...require("./../dist/standalone/src/components/dropdown-content/DropdownContent.driver"),
  ...require("./../dist/standalone/src/components/dropdown-option/DropdownOption.driver"),
  ...require("./../dist/standalone/src/components/icon-with-options/IconWithOptions.driver"),
  ...require("./../dist/standalone/src/components/image/image.driver"),
  ...require("./../dist/standalone/src/components/input/Input.driver"),
  ...require("./../dist/standalone/src/components/input-with-options/InputWithOptions.driver"),
  ...require("./../dist/standalone/src/components/label-with-options/LabelWithOptions.driver"),
  ...require("./../dist/standalone/src/components/linear-progress-bar/LinearProgressBar.driver"),
  ...require("./../dist/standalone/src/components/loadable/Loadable.driver"),
  ...require("./../dist/standalone/src/components/media-image/media-image.driver"),
  ...require("./../dist/standalone/src/components/menu-item/menu-item.driver"),
  ...require("./../dist/standalone/src/components/nav-stepper/NavStepper.driver"),
  ...require("./../dist/standalone/src/components/pagination/Pagination.driver"),
  ...require("./../dist/standalone/src/components/popover/Popover.driver"),
  ...require("./../dist/standalone/src/components/radio-button/RadioButton.driver"),
  ...require("./../dist/standalone/src/components/slider/Slider.driver"),
  ...require("./../dist/standalone/src/components/thumbnail/Thumbnail.driver"),
  ...require("./../dist/standalone/src/components/time-picker/TimePicker.driver"),
  ...require("./../dist/standalone/src/components/toggle-switch/ToggleSwitch.driver"),
  ...require("./../dist/standalone/src/components/tooltip/Tooltip.driver"),
  ...require("./../dist/standalone/src/components/video/Video.driver"),
  ...require("./../dist/standalone/src/components/deprecated/stylable-badge/Badge.driver"),
  ...require("./../dist/standalone/src/components/deprecated/button/Button.driver"),
  ...require("./../dist/standalone/src/components/deprecated/divider/Divider.driver"),
  ...require("./../dist/standalone/src/components/deprecated/label/Label.driver"),

};
