import { IconMetadata } from '../../types';

export const generalIconsMetadata: Array<IconMetadata> = [
  {
    'title': 'File',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'24': 'File'},
  }, {
    'title': 'FileAdd',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileAdd'},
  }, {
    'title': 'Data',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'18': 'DataSmall', '24': 'Data'},
  }, {
    'title': 'DataCollection',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DataCollection'},
  }, {
    'title': 'DateTime',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DateTime'},
  }, {
    'title': 'DateTimeBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DateTimeBold'},
  }, {
    'title': 'Folder',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'18': 'FolderSmall', '24': 'Folder'},
  }, {
    'title': 'AdminAccess',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AdminAccess'},
  }, {
    'title': 'AdminAccessBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AdminAccessBold'},
  }, {
    'title': 'Users',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'18': 'UsersSmall', '24': 'Users'},
  }, {
    'title': 'UsersBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UsersBold'},
  }, {
    'title': 'User',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'18': 'UserSmall', '24': 'User'},
  }, {
    'title': 'UserBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserBold'},
  }, {
    'title': 'UserEditBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserEditBold'},
  }, {
    'title': 'UserFormBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserFormBold'},
  }, {
    'title': 'UserPreviewBold',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserPreviewBold'},
  }, {
    'title': 'UserMenu',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserMenu'},
  }, {
    'title': 'UserPrivate',
    'category': 'User',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UserPrivate'},
  }, {
    'title': 'Sound',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Sound'},
  }, {
    'title': 'SoundBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SoundBold'},
  }, {
    'title': 'Music',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Music'},
  }, {
    'title': 'MusicBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MusicBold'},
  }, {
    'title': 'ImageGallery',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageGallery'},
  }, {
    'title': 'ImageGalleryBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageGalleryBold'},
  }, {
    'title': 'Image',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Image'},
  }, {
    'title': 'ImageBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageBold'},
  }, {
    'title': 'PlayCircle',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PlayCircle'},
  }, {
    'title': 'Video',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Video'},
  }, {
    'title': 'VideoBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'18': 'VideoBoldSmall', '24': 'VideoBold'},
  }, {
    'title': 'Crop',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Crop'},
  }, {
    'title': 'CropBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CropBold'},
  }, {
    'title': 'Brightness',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Brightness'},
  }, {
    'title': 'BrightnessBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BrightnessBold'},
  }, {
    'title': 'ImageEffect',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageEffect'},
  }, {
    'title': 'ImageEffectBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageEffectBold'},
  }, {
    'title': 'ColorDropBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ColorDropBold'},
  }, {
    'title': 'Border',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Border'},
  }, {
    'title': 'BorderBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BorderBold'},
  }, {
    'title': 'Corners',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Corners'},
  }, {
    'title': 'CornersBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CornersBold'},
  }, {
    'title': 'Shadow',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Shadow'},
  }, {
    'title': 'ShadowBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShadowBold'},
  }, {
    'title': 'Text',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'18': 'TextSmall', '24': 'Text'},
  }, {
    'title': 'TextBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TextBold'},
  }, {
    'title': 'TextMultiline',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TextMultiline'},
  }, {
    'title': 'TextMultilineBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TextMultilineBold'},
  }, {
    'title': 'ColorBucket',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ColorBucket'},
  }, {
    'title': 'ColorBucketBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ColorBucketBold'},
  }, {
    'title': 'Cut',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Cut'},
  }, {
    'title': 'CutBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CutBold'},
  }, {
    'title': 'PipetteFullBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PipetteFullBold'},
  }, {
    'title': 'Arrange',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Arrange'},
  }, {
    'title': 'ArrangeBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ArrangeBold'},
  }, {
    'title': 'MoveBackward',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveBackward'},
  }, {
    'title': 'MoveBackwardBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveBackwardBold'},
  }, {
    'title': 'MoveForward',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveForward'},
  }, {
    'title': 'MoveForwardBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveForwardBold'},
  }, {
    'title': 'SendToBack',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SendToBack'},
  }, {
    'title': 'SendToBackBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SendToBackBold'},
  }, {
    'title': 'SendToFront',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SendToFront'},
  }, {
    'title': 'SendToFrontBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SendToFrontBold'},
  }, {
    'title': 'SpacingBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SpacingBold'},
  }, {
    'title': 'Paragraph',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Paragraph'},
  }, {
    'title': 'ParagraphBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ParagraphBold'},
  }, {
    'title': 'Rotation',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Rotation'},
  }, {
    'title': 'Show',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'ShowSmall', '24': 'Show'},
  }, {
    'title': 'ShowBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShowBold'},
  }, {
    'title': 'Hide',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'HideSmall', '24': 'Hide'},
  }, {
    'title': 'HideBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HideBold'},
  }, {
    'title': 'Heart',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heart'},
  }, {
    'title': 'HeartBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HeartBold'},
  }, {
    'title': 'Star',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Star'},
  }, {
    'title': 'StarBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'StarBold'},
  }, {
    'title': 'Lock',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'LockSmall', '24': 'Lock'},
  }, {
    'title': 'LockBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'LockBold'},
  }, {
    'title': 'LockUnlocked',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'LockUnlockedSmall', '24': 'LockUnlocked'},
  }, {
    'title': 'LockUnlockedBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'LockUnlockedBold'},
  }, {
    'title': 'WarningSign',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WarningSign'},
  }, {
    'title': 'WarningSignBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WarningSignBold'},
  }, {
    'title': 'WarningCircle',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WarningCircle'},
  }, {
    'title': 'WarningCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WarningeCircleBold'},
  }, {
    'title': 'ConfirmCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ConfirmCircleBold'},
  }, {
    'title': 'AlertCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AlertCircleBold'},
  }, {
    'title': 'AlertCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AlertCircleBold'},
  }, {
    'title': 'MinusCircle',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MinusCircle'},
  }, {
    'title': 'Box',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Box'},
  }, {
    'title': 'BoxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BoxBold'},
  }, {
    'title': 'Button',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Button'},
  }, {
    'title': 'ButtonBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ButtonBold'},
  }, {
    'title': 'ImageButton',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ImageButton'},
  }, {
    'title': 'HorizontalLine',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalLine'},
  }, {
    'title': 'HorizontalLineBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalLineBold'},
  }, {
    'title': 'VerticalLine',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalLine'},
  }, {
    'title': 'VerticalLineBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalLineBold'},
  }, {
    'title': 'Strip',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Strip'},
  }, {
    'title': 'StripBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'StripBold'},
  }, {
    'title': 'Menu',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Menu'},
  }, {
    'title': 'MenuBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MenuBold'},
  }, {
    'title': 'HorizontalImage',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalImage'},
  }, {
    'title': 'HorizontalImageBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalImageBold'},
  }, {
    'title': 'VerticalImage',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalImage'},
  }, {
    'title': 'VerticalImageBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalImageBold'},
  }, {
    'title': 'SlideShow',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SlideShow'},
  }, {
    'title': 'SlideShowBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SlideShowBold'},
  }, {
    'title': 'List',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'List'},
  }, {
    'title': 'ListBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ListBold'},
  }, {
    'title': 'CheckboxList',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CheckboxList'},
  }, {
    'title': 'CheckboxListBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CheckboxListBold'},
  }, {
    'title': 'AddressInput',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AddressInput'},
  }, {
    'title': 'AddressInputBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AddressInputBold'},
  }, {
    'title': 'Captcha',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Captcha'},
  }, {
    'title': 'CaptchaBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CaptchaBold'},
  }, {
    'title': 'Column',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Column'},
  }, {
    'title': 'ColumnBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ColumnBold'},
  }, {
    'title': 'Dropdown',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Dropdown'},
  }, {
    'title': 'DropdownBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DropdownBold'},
  }, {
    'title': 'DropdownMenu',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DropdownMenu'},
  }, {
    'title': 'FullWidthSlider',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FullWidthSlider'},
  }, {
    'title': 'FullWidthSliderBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FullWidthSliderBold'},
  }, {
    'title': 'Html',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Html'},
  }, {
    'title': 'HtmlBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HtmlBold'},
  }, {
    'title': 'PaginationBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PaginationBold'},
  }, {
    'title': 'Scroll',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Scroll'},
  }, {
    'title': 'AppBuilder',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AppBuilder'},
  }, {
    'title': 'AppBuilderBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AppBuilderBold'},
  }, {
    'title': 'Checkbox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Checkbox'},
  }, {
    'title': 'CheckboxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CheckboxBold'},
  }, {
    'title': 'CustomTypeBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CustomTypeBold'},
  }, {
    'title': 'ESignatureBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ESignatureBold'},
  }, {
    'title': 'HorizontalMenu',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalMenu'},
  }, {
    'title': 'HorizontalMenuBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HorizontalMenuBold'},
  }, {
    'title': 'VerticalMenu',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalMenu'},
  }, {
    'title': 'VerticalMenuBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VerticalMenuBold'},
  }, {
    'title': 'RadioButton',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RadioButton'},
  }, {
    'title': 'RadioButtonBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RadioButtonBold'},
  }, {
    'title': 'Shape',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Shape'},
  }, {
    'title': 'ShapeBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShapeBold'},
  }, {
    'title': 'Switch',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Switch'},
  }, {
    'title': 'SwitchBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SwitchBold'},
  }, {
    'title': 'Vector',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Vector'},
  }, {
    'title': 'VectorBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VectorBold'},
  }, {
    'title': 'Boolean',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Boolean'},
  }, {
    'title': 'BooleanBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BooleanBold'},
  }, {
    'title': 'CheckboxList',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CheckboxList'},
  }, {
    'title': 'CheckboxListBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CheckboxListBold'},
  }, {
    'title': 'Repeater',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Repeater'},
  }, {
    'title': 'RepeaterBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RepeaterBold'},
  }, {
    'title': 'Slider',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Slider'},
  }, {
    'title': 'SliderBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SliderBold'},
  }, {
    'title': 'TableBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TableBold'},
  }, {
    'title': 'VideoTransparent',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VideoTransparent'},
  }, {
    'title': 'VideoTransparentBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VideoTransparentBold'},
  }, {
    'title': 'Widget',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Widget'},
  }, {
    'title': 'WidgetBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WidgetBold'},
  }, {
    'title': 'HoverBox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HoverBox'},
  }, {
    'title': 'HoverBoxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HoverBoxBold'},
  }, {
    'title': 'Input',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Input'},
  }, {
    'title': 'InputBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'InputBold'},
  }, {
    'title': 'RichTextBox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RichTextBox'},
  }, {
    'title': 'RichTextBoxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RichTextBoxBold'},
  }, {
    'title': 'TextBox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TextBox'},
  }, {
    'title': 'TextBoxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'TextBoxBold'},
  }, {
    'title': 'UploadButton',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UploadButton'},
  }, {
    'title': 'UploadButtonBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UploadButtonBold'},
  }, {
    'title': 'VideoBox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VideoBox'},
  }, {
    'title': 'VideoBoxBold',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'VideoBoxBold'},
  }, {
    'title': 'Anchor',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Anchor'},
  }, {
    'title': 'ProfileWidget',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ProfileWidget'},
  }, {
    'title': 'QuickActionBar',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'QuickActionBar'},
  }, {
    'title': 'Rss',
    'category': 'Components',
    'description': '', 'tags': [],
    'sizes': {'24': 'Rss'}
  }, {
    'title': 'Seo',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Seo'},
  }, {
    'title': 'SocialBar',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SocialBar'},
  }, {
    'title': 'Popup',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Popup'},
  }, {
    'title': 'Footer',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Footer'},
  }, {
    'title': 'Header',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Header'},
  }, {
    'title': 'WixForum',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixForum'},
  }, {
    'title': 'WixForms',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixForms'},
  }, {
    'title': 'WixFormsBold',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixFormsBold'},
  }, {
    'title': 'WixDevCenter',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixDevCenter'},
  }, {
    'title': 'WixDevCenterBold',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixDevCenterBold'},
  }, {
    'title': 'WixStores',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixStores'},
  }, {
    'title': 'WixRestaurants',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixRestaurants'},
  }, {
    'title': 'WixHotels',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixHotels'},
  }, {
    'title': 'Child',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Child'},
  }, {
    'title': 'ChildBold',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChildBold'},
  }, {
    'title': 'Parent',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Parent'},
  }, {
    'title': 'PagesBold',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PagesBold'},
  }, {
    'title': 'PageDynamic',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PageDynamic'},
  }, {
    'title': 'Page',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Page'},
  }, {
    'title': 'PageBold',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PageBold'},
  }, {
    'title': 'PageAdd',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PageAdd'},
  }, {
    'title': 'FileCss',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileCss'},
  }, {
    'title': 'FileHtml',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileHtml'},
  }, {
    'title': 'FileJs',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileJs'},
  }, {
    'title': 'FileJson',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileJson'},
  }, {
    'title': 'FileJsw',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FileJsw'},
  }, {
    'title': 'PageSpecial',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PageSpecial'},
  }, {
    'title': 'Router',
    'category': 'Page',
    'description': '',
    'tags': [],
    'sizes': {'18': 'RouterSmall', '24': 'Router'},
  }, {
    'title': 'Cloud',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'18': 'CloudSmall', '24': 'Cloud'},
  }, {
    'title': 'CloudBold',
    'category': 'Files & Data',
    'description': '',
    'tags': [],
    'sizes': {'18': 'CloudBoldSmall', '24': 'CloudBold'},
  }, {
    'title': 'Home',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'18': 'HomeSmall', '24': 'Home'},
  }, {
    'title': 'HomeBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HomeBold'},
  }, {
    'title': 'Browser',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Browser'},
  }, {
    'title': 'BrowserBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BrowserBold'},
  }, {
    'title': 'Mobile',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Mobile'},
  }, {
    'title': 'MobileBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MobileBold'},
  }, {
    'title': 'Settings',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'18': 'SettingsSmall', '24': 'Settings'},
  }, {
    'title': 'SettingsBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SettingsBold'},
  }, {
    'title': 'AppMarket',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AppMarket'},
  }, {
    'title': 'AppMarketBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AppMarketBold'},
  }, {
    'title': 'Chat',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Chat'},
  }, {
    'title': 'ChatBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChatBold'},
  }, {
    'title': 'MapPin',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MapPin'},
  }, {
    'title': 'MapPinBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MapPinBold'},
  }, {
    'title': 'Tag',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Tag'}
    }, {
    'title': 'Phone',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Phone'},
  }, {
    'title': 'PhoneBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PhoneBold'},
  }, {
    'title': 'ShoppingCart',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShoppingCart'},
  }, {
    'title': 'ShoppingCartBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShoppingCartBold'},
  }, {
    'title': 'Hint',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Hint'},
  }, {
    'title': 'Email',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Email'},
  }, {
    'title': 'EmailBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'EmailBold'},
  }, {
    'title': 'Badge',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Badge'},
  }, {
    'title': 'Globe',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Globe'},
  }, {
    'title': 'CustomBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CustomBold'},
  }, {
    'title': 'CalendarBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CalendarBold'},
  }, {
    'title': 'MandatoryCircle',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MandatoryCircle'},
  }, {
    'title': 'ExternalLink',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ExternalLink'},
  }, {
    'title': 'ExternalLinkBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ExternalLinkBold'},
  }, {
    'title': 'Desktop',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Desktop'},
  }, {
    'title': 'ArticleBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ArticleBold'},
  }, {
    'title': 'BookBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BookBold'},
  }, {
    'title': 'BookOpenBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BookOpenBold'},
  }, {
    'title': 'FormEditBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FormEditBold'},
  }, {
    'title': 'FormBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'FormBold'},
  }, {
    'title': 'Undo',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Undo'}
    }, {
    'title': 'Redo',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Redo'},
  }, {
    'title': 'Delete',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Delete'},
  }, {
    'title': 'DeleteBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DeleteBold'},
  }, {
    'title': 'Edit',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Edit'},
  }, {
    'title': 'EditBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'EditBold'},
  }, {
    'title': 'MoveToTrash',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'MoveToTrash'},
  }, {
    'title': 'Reset',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Reset'},
  }, {
    'title': 'Replace',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Replace'},
  }, {
    'title': 'ReplaceBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ReplaceBold'},
  }, {
    'title': 'Search',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Search'},
  }, {
    'title': 'SearchBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SearchBold'},
  }, {
    'title': 'ZoomIn',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ZoomIn'},
  }, {
    'title': 'ZoomInBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ZoomInBold'},
  }, {
    'title': 'ZoomOut',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ZoomOut'},
  }, {
    'title': 'ZoomOutBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ZoomOutBold'},
  }, {
    'title': 'UrlLink',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'18': 'UrlLinkSmall', '24': 'UrlLink'},
  }, {
    'title': 'UrlLinkBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UrlLinkBold'},
  }, {
    'title': 'UrlLinkAdd',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UrlLinkAdd'},
  }, {
    'title': 'LinkProperties',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'18': 'LinkPropertiesSmall', '24': 'LinkProperties'},
  }, {
    'title': 'UnlinkProperties',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'18': 'UnlinkPropertiesSmall', '24': 'UnlinkProperties'},
  }, {
    'title': 'UrlUnlink',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UrlUnlink'},
  }, {
    'title': 'UrlUnlinkBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UrlUnlinkBold'},
  }, {
    'title': 'AddCircle',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AddCircle'},
  }, {
    'title': 'Design',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Design'},
  }, {
    'title': 'DesignBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DesignBold'},
  }, {
    'title': 'Download',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Download'},
  }, {
    'title': 'DownloadBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DownloadBold'},
  }, {
    'title': 'Upload',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Upload'},
  }, {
    'title': 'UploadBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UploadBold'},
  }, {
    'title': 'SplitColumns',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SplitColumns'},
  }, {
    'title': 'Save',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Save'},
  }, {
    'title': 'SaveBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SaveBold'},
  }, {
    'title': 'ApplyTo',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ApplyTo'},
  }, {
    'title': 'Copy',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Copy'},
  }, {
    'title': 'CopyBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CopyBold'},
  }, {
    'title': 'Duplicate',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Duplicate'},
  }, {
    'title': 'DuplicateBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DuplicateBold'},
  }, {
    'title': 'Paste',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Paste'},
  }, {
    'title': 'PasteBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'PasteBold'},
  }, {
    'title': 'Rename',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Rename'},
  }, {
    'title': 'RenameBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'RenameBold'},
  }, {
    'title': 'Group',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Group'},
  }, {
    'title': 'GroupBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'GroupBold'},
  }, {
    'title': 'Ungroup',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Ungroup'},
  }, {
    'title': 'UngroupBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'UngroupBold'},
  }, {
    'title': 'PinBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'18': 'PinBoldSmall', '24': 'PinBold'},
  }, {
    'title': 'ResetShapeBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ResetShapeBold'},
  }, {
    'title': 'Twitter',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Twitter'},
  }, {
    'title': 'Pinterest',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Pinterest'},
  }, {
    'title': 'Facebook',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Facebook'},
  }, {
    'title': 'Blogger',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Blogger'},
  }, {
    'title': 'Flash',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Flash'},
  }, {
    'title': 'Skype',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Skype'},
  }, {
    'title': 'Tumblr',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Tumblr'},
  }, {
    'title': 'Vimeo',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Vimeo'},
  }, {
    'title': 'Youtube',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Youtube'},
  }, {
    'title': 'Soundcloud',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Soundcloud'},
  }, {
    'title': 'Spotify',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Spotify'},
  }, {
    'title': 'ITunes',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ITunes'},
  }, {
    'title': 'Paypal',
    'category': 'Brand',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Paypal'},
  }, {
    'title': 'HelpCircle',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HelpCircle'}
  }, {
    'title': 'HelpBold',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'HelpBold'}
  }, {
    'title': 'ChevronUpSmall',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'18': 'ChevronUpSmall'}
  }, {
    'title': 'ChevronDownSmall',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'18': 'ChevronDownSmall'}
  }, {
    'title': 'ChevronRightSmall',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'18': 'ChevronRightSmall'}
  }, {
    'title': 'ChevronLeftSmall',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'18': 'ChevronLeftSmall'}
  }, {
    'title': 'ChevronUp',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChevronUp'}
  }, {
    'title': 'ChevronDown',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChevronDown'}
  }, {
    'title': 'ChevronRight',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChevronRight'}
  }, {
    'title': 'ChevronLeft',
    'category': 'Arrows',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ChevronLeft'}
  }, {
    'title': 'Add',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Add'}
  }, {
    'title': 'AddBold',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AddBold'}
  }, {
    'title': 'ContextMenu',
    'category': 'Actions',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ContextMenu'}
  }, {
    'title': 'CloseButton',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'CloseButton'}
  }, {
    'title': 'Heading1',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading1'}
  }, {
    'title': 'Heading2',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading2'}
  }, {
    'title': 'Heading3',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading3'}
  }, {
    'title': 'Heading4',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading4'}
  }, {
    'title': 'Heading5',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading5'}
  }, {
    'title': 'Heading6',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Heading6'}
  }, {
    'title': 'WixChat',
    'category': 'Wix Brands',
    'description': '',
    'tags': [],
    'sizes': {'24': 'WixChat'}
  }, {
    'title': 'Dashboard',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Dashboard'}
  }, {
    'title': 'Table',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Table'}
  }, {
    'title': 'ShapeCropBold',
    'category': 'Composer',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ShapeCropBold'}
  }, {
    'title': 'Lightbox',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Lightbox'}
  }, {
    'title': 'SocialBar',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'SocialBar'}
  }, {
    'title': 'BlockQuote',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'BlockQuote'}
  }, {
    'title': 'MandatoryCircleSmall',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'MandatoryCircleSmall'}
  }, {
    'title': 'PlayBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'18': 'PlayBoldSmall'}
  }, {
    'title': 'StopBold',
    'category': 'Media',
    'description': '',
    'tags': [],
    'sizes': {'18': 'StopBoldSmall'}
  }, {
    'title': 'ESignature',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ESignature'}
  }, {
    'title': 'AnimatedSlide',
    'category': 'Components',
    'description': '',
    'tags': [],
    'sizes': {'24': 'AnimatedSlide'}
  }, {
    'title': 'Info',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Info'}
  }, {
    'title': 'Adjustments',
    'category': 'General',
    'description': '',
    'tags': [],
    'sizes': {'24': 'Adjustments'}
  }, {
    'title': 'SelectedCircleSmall',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'18': 'SelectedCircleSmall'}
  }, {
    'title': 'DismissCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'DismissCircleBold'}
  }, {
    'title': 'ConfirmCircleBold',
    'category': 'Status',
    'description': '',
    'tags': [],
    'sizes': {'24': 'ConfirmCircleBold'}
  },
]

export default generalIconsMetadata;
